pull_request_rules:
  - name: dispatch-on-title
    conditions:
      - base = main
      - "title ~= DISPATCHME"
    actions:
      github_actions:
        workflow:
          dispatch:
            - workflow: mgf-priv.yml
