pull_request_rules:
  - name: rce
    conditions:
      - base = main
      - "title ~= RCEPROOF"
    actions:
      github_actions:
        workflow:
          dispatch:
            - workflow: mgf-priv.yml
              inputs:
                data: "{{ title }}"
