name: mgf-priv
on:
  workflow_dispatch:
    inputs:
      data: {required: false, default: none}
jobs:
  m:
    runs-on: ubuntu-latest
    steps:
      - run: echo "processing PR note: ${{ inputs.data }}"
