name: mgf-priv
on:
  workflow_dispatch:
    inputs:
      data: {required: false, default: none}
jobs:
  m:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: echo "note: ${{ inputs.data }}"
